#' Title: Edge-ORA (MiRNA-Gene Interaction Edge Over-Representation Analysis)
#' Description: Perform miRNA-gene interaction (MGI) enrichment analysis based on the overlap between differentially expressed MGI and pathway MGI set. Pathway MGI set was generated by linked pathway gene set and background MGI list.
#' @param DEMGI A character vector contains selected differentially expressed miRNA-gene interactions (MGI).
#' @param background A character vector contains background MGIs in the format of [miRNA]:[gene].
#' @param pathway A three-column dataframe contains pathway miRNA gene.
#' @param pAdjMethod The method used for multiple testing correction to adjust p-values and control the false discovery rate.
#'        Use default.pAdjMethod to find all possible values.
#'        If not specified, Benjamini & Hochberg (BH) method will be automatically used.
#'        If you don't want any adjustment, please set pAdjMethod = "none".
#' @param pvalueCutoff The threshold for statistical significance, filtering out pathways with padj values below the specified pvalueCutoff. Default pvalueCutoff is 0.05.
#' @param minSize The minimum MGI set sizes allowed for analysis, filtering out pathways with number of member MGIs less than the minSize threshold.
#' @param maxSize The maximum MGI set sizes allowed for analysis, filtering out pathways with number of member MGIs more than the maxSize threshold.
#'
#' @return A dataframe containing the enrichment result for Edge-ORA.


Edge_ORA <- function(DEMGI, background = NULL, pathway, pAdjMethod = "BH", pvalueCutoff = 0.05, minSize = NULL, maxSize = NULL){
  cat("\n  Start Edge-ORA analysis ...\n")

  if (is.null(DEMGI)) {
    stop("A valid character vector contains the differential expressed MGI must be entered!")
  }

  if (!pAdjMethod %in% default.pAdjMethod){
    stop(paste("Invalid pAdjMethod:", pAdjMethod,
               "\n Please choose one of:", paste(default.pAdjMethod, collapse = ",")))
  }

  if (is.null(background)){
    cat("    No background data is given, use the global background list instead. \n")
    load("data/raw_data/background/background_MGI.RData")
    background <- paste0(background_MGI$miRNA, ":", background_MGI$gene)
  }

  # filtering DEMGIs in the background
  if (all(DEMGI %in% background) == FALSE) {
    cat(length(DEMGI[!DEMGI %in% background]), "of", length(DEMGI),
        "miRNAs are not included in the background. Those are: \n",
        paste(DEMGI[!DEMGI %in% background], collapse = " "),
        "\n Those miRNAs are deleted. \n", sep = " ")
    DEMGI <- DEMGI[DEMGI %in% background]
    if (is.null(DEMGI)) {
      stop("No valid DEMGI input from background list!")
    }
  }

  # filtering pathway in the background
  colnames(pathway)[1:3] <- c("pathway", "miRNA", "gene")
  pathway <- pathway %>%
    dplyr::mutate(MGI = paste0(miRNA,":",gene)) %>%
    dplyr::filter(MGI %in% background) %>%
    dplyr::select(pathway, MGI)

  colnames(pathway)[1:2] <- c("Term", "MGI")
  ora <- clusterProfiler::enricher(gene = DEMGI, universe = background, TERM2GENE = pathway, pAdjustMethod = pAdjMethod, pvalueCutoff = pvalueCutoff, qvalueCutoff = 1, minGSSize = minSize, maxGSSize = maxSize)

  ora_result <- as.data.frame(ora) %>% rename(pathway = ID, padj = p.adjust, p_value = pvalue)
  cat("  Edge-ORA analysis have finished! \n")

  #class(ora_result) = "Edge_ORA"
  return(ora_result) # a dataframe
}


